version: "2"

run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - vendor

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - revive
    - misspell
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

issues:
  exclude-rules:
    - linters:
        - revive
      text: "^package-comments:"

formatters:
  settings:
    gofmt:
      simplify: true
